"""Layer contract.

A layer turns one piece of evidence into a (log) likelihood *shape*
``loglik[i, j] = log s(x)``, s(x) ∝ P(evidence | box in cell x), defined up to
an additive constant.

* NaN means "no information here": the cell gets likelihood ratio 1.
* ``reliability`` r is the probability that the evidence model is right (the
  hint is read correctly, the flight match is right, ...). Fusion uses the
  calibrated robust mixture

      L(x) = r * s(x) / E[s] + (1 - r)

  where E[s] is the mean of s over the search domain (uniform prior over
  Norwegian land). This is exactly the likelihood of "evidence generated by
  the model with prob. r, by something unrelated to the location with prob.
  1 - r": for a 0/1 constraint on a region B it gives P(box in B) ≈ r (plus
  (1 - r) x area share of B), whatever the size of B. An unreliable hint can
  therefore never zero a cell out (L >= 1 - r).
* Layers that come from the same underlying observation share an
  ``independence_group``; fusion takes the reliability-weighted mean of their
  log-likelihoods inside a group instead of summing, to avoid double counting.
* hard=True layers: cells with loglik == -inf are excluded outright (used only
  for near-certain facts, e.g. "in Norway").
"""
from dataclasses import dataclass, field

import numpy as np


@dataclass
class LayerResult:
    name: str
    loglik: np.ndarray
    reliability: float
    independence_group: str
    description: str = ""
    sources: list = field(default_factory=list)
    hard: bool = False

    def shape_s(self):
        """s(x) = exp(loglik - max) with NaN kept."""
        ll = np.array(self.loglik, dtype=float)
        fin = np.isfinite(ll)
        if not fin.any():
            return np.full_like(ll, np.nan)
        return np.exp(ll - np.max(ll[fin]))

    def robust(self, domain=None):
        """log L(x) of the calibrated mixture (see module docstring)."""
        ll = np.array(self.loglik, dtype=float)
        if self.hard:
            return np.where(np.isneginf(ll), -np.inf, 0.0)
        s = self.shape_s()
        dom = np.isfinite(s) if domain is None else (domain & np.isfinite(s))
        if not dom.any():
            return np.zeros_like(s)
        m = float(np.mean(s[dom]))
        if m <= 0:
            return np.zeros_like(s)
        s = np.where(np.isnan(s), m, s)
        r = float(np.clip(self.reliability, 0.0, 0.999))
        with np.errstate(divide="ignore"):
            return np.log(r * s / m + (1.0 - r))


def gaussian_ll(x, mu, sigma):
    return -0.5 * ((np.asarray(x) - mu) / sigma) ** 2


def band_ll(x, lo, hi, soft):
    """0 inside [lo, hi], Gaussian fall-off with scale `soft` outside."""
    x = np.asarray(x, float)
    d = np.where(x < lo, lo - x, np.where(x > hi, x - hi, 0.0))
    return -0.5 * (d / soft) ** 2
